---
title: "P8158 Final"
author: "Waveley Qiu (wq2162)"
date: "2022-04-14"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(haven)
library(psych)
library(GPArotation)
library(naniar)
library(gtsummary)
```


```{r}
dataset <- readxl::read_excel("data/Athlete_Non-Athlete MH Survey - ALL DATA.xlsx", 
                              sheet = "athlete_fin") %>% 
  slice(-1) %>%   
  replace_with_na_all(condition = ~.x == "999") 

dataset_no_na <- dataset %>% 
  select(-c("SHIELD_DTS", "DATE")) %>% 
  na.omit()

athletes <- dataset %>% filter(ATHLETE_YN == "1") %>% select(-c("SHIELD_DTS", "DATE"))
athletes %>% colnames()

athletes_no_na <- athletes %>% select(-c("SHIELD_DTS")) %>% na.omit()

non_athletes <- dataset %>% filter(ATHLETE_YN == "2")
```

## Construct Reliability

```{r}
features <- athletes[,15:67] %>% map_df(., as.numeric) 
# %>% select(!ends_with("_HRS"))
athlete_parallel <- fa.parallel(features, cor = "poly", fa = "pc")

# broken :(
```


## EFA

```{r}

```


